### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by AciDCooL** [mdhiggins/sonarr-sma#32]
Hi,

I'm running mdhiggins/sonarr-sma:latest but can't run sma. After a little digging, manual execution of postsonarr.py I get: 

`root@sonarr:/usr/local/sma# python3 postSonarr.py 
Traceback (most recent call last):
  File "postSonarr.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Easy fix to add this I suppose, just wanting to bring this to your attention.

**Comment by mdhiggins** [comment]
Are you running using the virtual environment where all the dependencies are installed or just the system python

**Comment by AciDCooL** [comment]
I feel like a complete idiot, there is a reason why there is a postSonarr.sh. I made a config mistake a while back that's why is not being executed.

`2021-11-29 13:40:02 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 171, in <module>
    settings = ReadSettings()
  File "/usr/local/sma/resources/readsettings.py", line 591, in __init__
    self.readConfig(config)
  File "/usr/local/sma/resources/readsettings.py", line 770, in readConfig
    self.embedonlyinternalsubs = config.getboolean(section, 'embed-only-internal-subs')
  File "/usr/lib/python3.6/configparser.py", line 829, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 809, in _get_conv
    **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.6/configparser.py", line 1155, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: Falsei`


Thanks for pushing me in the right direction with your question :)
