### ISSUE TITLE
Error in "/usr/local/sma/resources/mediaprocessor.py", line 261, in videoStreamTitle

### ISSUE THREAD

**Issue by henryjb99** [mdhiggins/sonarr-sma#38]
Getting the following error when converting from MKV to MP4. I think it is related to [https://github.com/mdhiggins/sonarr-sma/issues/29](url). However, this fix has not been pulled into the latest sonarr and radarr containers.

Log file:
2022-06-11 21:03:22 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2022-06-11 21:03:22 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2022-06-11 21:03:22 - resources.readsettings - DEBUG - Loading default config file.
2022-06-11 21:03:22 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - environ({'SMA_UPDATE': 'false', 'sonarr_episodefile_sourcepath': '/shared/Downloaded/sonarr/For.All.Mankind.S03E01.720p.WEB.H264-GGEZ[rarbg]/for.all.mankind.s03e01.720p.web.h264-ggez.mkv', 'sonarr_isupgrade': 'False', 'PUID': '0', 'sonarr_episodefile_id': '133188', 'HOSTNAME': '3c4c6fe27088', 'LANGUAGE': 'en_US.UTF-8', 'sonarr_episodefile_relativepath': 'Season 3/For All Mankind - S03E01 - Polaris [WEBDL-720p].mkv', 'sonarr_series_id': '158', 'sonarr_series_tvdbid': '356202', 'XDG_CONFIG_HOME': '/config/xdg', 'No_PreLoadSQLite': 'true', 'sonarr_episodefile_episodeids': '169045', 'sonarr_download_client': 'qBittorent', 'sonarr_episodefile_path': '/shared/TV Shows/For All Mankind/Season 3/For All Mankind - S03E01 - Polaris [WEBDL-720p].mkv', 'No_SQLiteFunctions': 'true', 'sonarr_episodefile_sourcefolder': '/shared/Downloaded/sonarr/For.All.Mankind.S03E01.720p.WEB.H264-GGEZ[rarbg]', 'PWD': '/app/sonarr/bin', 'sonarr_episodefile_qualityversion': '1', 'sonarr_episodefile_quality': 'WEBDL-720p', 'HOME': '/root', 'LANG': 'en_US.UTF-8', 'sonarr_episodefile_seasonnumber': '3', 'sonarr_series_path': '/shared/TV Shows/For All Mankind', 'sonarr_episodefile_episodeairdatesutc': '6/10/2022 4:00:00 AM', 'PGID': '0', 'sonarr_episodefile_episodecount': '1', 'sonarr_series_title': 'For All Mankind', 'sonarr_download_client_type': 'qBittorrent', 'SMA_FFMPEG_URL': 'https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz', 'sonarr_series_tvmazeid': '41414', 'sonarr_episodefile_episodetitles': 'Polaris', 'sonarr_episodefile_episodenumbers': '1', 'TERM': 'xterm', 'sonarr_eventtype': 'Download', 'sonarr_episodefile_episodeairdates': '2022-06-10', 'SHLVL': '1', 'SMA_PATH': '/usr/local/sma', 'sonarr_series_imdbid': 'tt7772588', 'SMA_RS': 'Sonarr', 'CWD': '/', 'sonarr_series_type': 'Standard', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'No_SQLiteXmlConfigFile': 'true', 'SONARR_BRANCH': 'main', 'sonarr_download_id': '60DF44E2FD02C77E3F245FFB732B89E55D51A17E', 'No_Expand': 'true', 'sonarr_episodefile_scenename': 'For.All.Mankind.S03E01.720p.WEB.H264-GGEZ', 'OLDPWD': '/run/s6/services/sonarr', 'sonarr_episodefile_releasegroup': 'GGEZ', '_': '/usr/local/sma/venv/bin/python3'})
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - Input file: /shared/TV Shows/For All Mankind/Season 3/For All Mankind - S03E01 - Polaris [WEBDL-720p].mkv.
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - Original name: For.All.Mankind.S03E01.720p.WEB.H264-GGEZ.
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - TVDB ID: 356202.
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - Season: 3 episode: 1.
2022-06-11 21:03:22 - SonarrPostProcess - DEBUG - Sonarr series ID: 158.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Processing /shared/TV Shows/For All Mankind/Season 3/For All Mankind - S03E01 - Polaris [WEBDL-720p].mkv.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Process started.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Found forced in stream title, setting forced disposition to True.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Input Data
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - {
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "pix_fmt": "yuv420p",
        "profile": "high",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709",
            "side_data_list": [
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                }
            ]
        },
        "dimensions": "1356x678",
        "level": 3.2,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "eac3",
            "bitrate": 768000,
            "channels": 6,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        }
    ],
    "subtitle": [
        {
            "index": 2,
            "codec": "subrip",
            "disposition": "+default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        },
        {
            "index": 3,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        },
        {
            "index": 4,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ara"
        },
        {
            "index": 5,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "bul"
        },
        {
            "index": 6,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "zho"
        },
        {
            "index": 7,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "zho"
        },
        {
            "index": 8,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "zho"
        },
        {
            "index": 9,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ces"
        },
        {
            "index": 10,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "dan"
        },
        {
            "index": 11,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "nld"
        },
        {
            "index": 12,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "est"
        },
        {
            "index": 13,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "spa"
        },
        {
            "index": 14,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "fin"
        },
        {
            "index": 15,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "fra"
        },
        {
            "index": 16,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "fra"
        },
        {
            "index": 17,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "deu"
        },
        {
            "index": 18,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ell"
        },
        {
            "index": 19,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "heb"
        },
        {
            "index": 20,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "hin"
        },
        {
            "index": 21,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "hun"
        },
        {
            "index": 22,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ind"
        },
        {
            "index": 23,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ita"
        },
        {
            "index": 24,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "jpn"
        },
        {
            "index": 25,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "kor"
        },
        {
            "index": 26,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "spa"
        },
        {
            "index": 27,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "lav"
        },
        {
            "index": 28,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "lit"
        },
        {
            "index": 29,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "msa"
        },
        {
            "index": 30,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "nor"
        },
        {
            "index": 31,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "pol"
        },
        {
            "index": 32,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "por"
        },
        {
            "index": 33,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "por"
        },
        {
            "index": 34,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "rus"
        },
        {
            "index": 35,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "slk"
        },
        {
            "index": 36,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "slv"
        },
        {
            "index": 37,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "swe"
        },
        {
            "index": 38,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "tam"
        },
        {
            "index": 39,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "tel"
        },
        {
            "index": 40,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "tha"
        },
        {
            "index": 41,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "tur"
        },
        {
            "index": 42,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "ukr"
        },
        {
            "index": 43,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "vie"
        }
    ],
    "attachment": []
}
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Reading video stream.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Video codec detected: h264.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Profile: high.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Stream is not HDR, color parameter bt709 does not match ['bt2020nc'] [hdr-['bt2020nc']].
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Pool of video codecs is ['h265', 'hevc'].
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Total bitrate is 3590492.0.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Total audio bitrate is 768000.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Estimated video bitrate is 2822492.0.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Using video bitrate ratio of 1.000000, which results in 2681.367400 changing to 2681.367400.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Overriding video bitrate. Codec cannot be copied because video bitrate is too high [video-max-bitrate].
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video width is over the max width, it will be downsampled. Video stream can no longer be copied [video-max-width].
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Source bit-depth 8, output 0, using depth 8.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video codec: h265.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video bitrate: 2500.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video CRF: -1.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video maxrate: None.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video bufsize: None.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video level: 0.0.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video profile: None.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video preset: None.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video pix_fmt: None.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video field order: progressive.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video width: 1280.
2022-06-11 21:03:22 - resources.mediaprocessor - DEBUG - Video debug video.max-bitrate.max-width.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Video codec parameters None.
2022-06-11 21:03:22 - resources.mediaprocessor - INFO - Creating h265 video stream from source stream 0.
2022-06-11 21:03:22 - resources.mediaprocessor - ERROR - Unable to generate options, unexpected exception occurred.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 128, in process
    options, preopts, postopts, ripsubopts, downloaded_subs = self.generateOptions(inputfile, info=info, original=original, tagdata=tagdata)
  File "/usr/local/sma/resources/mediaprocessor.py", line 828, in generateOptions
    video_settings['title'] = self.videoStreamTitle(info.video, video_settings, hdr=vHDR)
  File "/usr/local/sma/resources/mediaprocessor.py", line 261, in videoStreamTitle
    if width >= 7600 or height >= 4300:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
2022-06-11 21:03:22 - SonarrPostProcess - INFO - Processing returned False.
2022-06-11 21:03:22 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 325, in <module>
    sys.exit(1)
SystemExit: 1
--------------------------------------------------------------------------------------------------------------------------

autoProcess.ini
[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = 
hwaccel-decoders = 
hwdevices = vaapi:/dev/dri/renderD12
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
temp-output = False
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0777
uid = 1000
gid = 1000

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h265, hevc
max-bitrate = 2500
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 1280
profile = 
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
aac-adtstoasc = False
ignored-dispositions = 
unique-dispositions = False
stream-codec-combinations = 

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based = 
languages = 
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 
remove-bitstream-subs = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.Subliminal]
download-subs = False
download-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Sonarr]
host = 127.0.0.1
port = 8989
apikey = XXXXXXXXXXXXXXXXXXXXX
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Radarr]
host = 127.0.0.1
port = 7878
apikey = XXXXXXXXXXXXXXXXXXXXXXXX
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = XXXXXXXXXXXXXXXXXXXXXX
port = 32400
refresh = False
token = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by mdhiggins** [comment]
This error was fixed recently just update to the latest version

**Comment by henryjb99** [comment]
Ok, repulling the image doesnt seem to help. I think this is related to my VPN not having any healthcheck. It seems to fail pulling in the latest copy of SMA. If I manually pull in the copy, everything works fine.

Will play around to add some healthchecks and get things running properly. Thanks

**Comment by mdhiggins** [comment]
The docker containers rebuild weekly. Just set the SMA_UPDATE environment variable to true and restart the container to pull from the repo

**Comment by henryjb99** [comment]
Yup, that worked. Thank you!
